set(PROVIDER "github")
set(TAG "main")
set(FOLDER "/")
set(FILENAME "ModulesList.cmake")
cmmm_define_module(Example1 LOCAL /example1/Example1.cmake)
cmmm_define_module(Example2 LOCAL /example1/Example2.cmake)
cmmm_define_module(Remote REMOTE https://github.com/cmake-tools/cmmm.test/blob/main/remote/Remote.cmake)
cmmm_define_module(Remote2 REMOTE gh:cmake-tools/cmmm.test FILEPATH Remote.cmake)
