set(PROVIDER "github")
set(TAG "main")
set(FOLDER "main")
set(FILENAME "ModulesList.cmake")
cmmm_define_module(Example1 LOCAL /example1/Example1.cmake)
cmmm_define_module(Example2 LOCAL /example1/Example2.cmake)
